//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Project_Example
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayList_Song
    {
        public int Id { get; set; }
        public int SongId { get; set; }
        public int PlayListId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public int Status { get; set; }
    
        public virtual PlayList PlayList { get; set; }
        public virtual Song Song { get; set; }
    }
}
